---
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Coderzc's Blog
subtitle: 'Write the code. Change the world.'
description: 'Write the code. Change the world.'
keywords: 分布式,容器化,linux,操作系统,高并发,机器学习,网络,数据库,java,golang,rust,python
author: coderzc
timezone: 'Asia/Shanghai'

# Internationalization (i18n) Setting
#language: # At present, only en、cn and tw are supported. You can customize the language，refer to `languages/en.yml`.
#  - en
#  - cn
#langselect:
#  enable: false # If open, it will automatically generation lang-select button.This button can jump in articles in different languages, but the articles must have the same name.
#  options: # langselect button display options
#    en: English
#    cn: 简体中文
    # tw: 正體中文


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://coderzc.github.io/blog
root: /blog/
permalink: :year/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# CDN Setting
## Docs: https://www.jsdelivr.com/?docs=gh
## If Github Pages deploy，you can ues jsdelivr settings
#
# jsdelivr:
#   jsdelivr_url: https://cdn.jsdelivr.net/gh/
#   github_username: coderzc


# Custom Setting Start

# Site settings
SEOTitle: coderzc blog
email: zc1217zc@126.com
header-img: http://h2.ioliu.cn/bing/PingganVillage_ZH-CN10035092925_1920x1080.jpg?imageslim
#archives-img: img/header_img/post2.jpg,img/header_img/post3.jpg,img/header_img/post.jpg,img/header_img/post4.jpg,img/header_img/post5.jpg,img/header_img/post6.jpg
archives-img: >-
  https://gitee.com/coderzc/blogimage/raw/master/post4.jpg,
  http://h2.ioliu.cn/bing/FreshSalt_ZH-CN12818759319_1920x1080.jpg?imageslim,
  http://h2.ioliu.cn/bing/RainierMilkyWay_ZH-CN9404321904_1920x1080.jpg?imageslim,
  https://gitee.com/coderzc/blogimage/raw/master/post3.jpg,
  https://h2.ioliu.cn/bing/BulgariaPerseids_EN-AU11585904087_1920x1080.jpg?imageslim,
  https://h2.ioliu.cn/bing/MundoFalls_ROW9309097946_1920x1080.jpg?imageslim,
  https://h2.ioliu.cn/bing/MilkyWayLadakh_ZH-CN7734727282_1920x1080.jpg?imageslim,
  https://h2.ioliu.cn/bing/TrilliumLake_ZH-CN4079462365_1920x1080.jpg?imageslim,
  https://h2.ioliu.cn/bing/LuciolaCruciata_ZH-CN9063767400_1920x1080.jpg?imageslim,
  https://h2.ioliu.cn/bing/MalhamStars_ZH-CN4163177154_1920x1080.jpg?imageslim,

# Favicon settings
favicon: img/avatar/coderzc.png


# Signature Setup
signature: true # show signature
signature-img: img/signature/vincent-white.png


# Wave settings
wave: false


# SNS Settings
# RSS: true
github_username: coderzc
# facebook_username:  yourAccount
# linkedin_username:  yourAccount
# zhihu_username: WVincen
#weibo_username: WVincen


# Sidebar Settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "Write the code. Change the world."
sidebar-avatar:     img/avatar/coderzc.png
widgets:
  - visitor   # busuanzi: https://busuanzi.ibruce.info/
  - featured-tags
  - short-about
  - recent-posts
  - friends-blog
  - archive
  - category


# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true   # whether or not using Feature-Tags
featured-condition-size: 0    # A tag will be featured if the size of it is more than this condition value

## Friends
#friends: [
#  {
#    title: "V_Vincen",
#    href: "https://v-vincen.life/"
#  },{
#    title: "Bean Tech",
#    href: "http://beantech.org"
#  },{
#    title: "Hux Blog",
#    href: "http://huangxuan.me"
#  },{
#    title: "Hexo",
#    href: "https://hexo.io/"
#  }
#]


# Comment Settings

## Gitalk Settings
## Doc:https://github.com/gitalk/gitalk/blob/master/readme-cn.md
##
#gitalk:
#  owner: coderzc                          # 'GitHub repo owner'
#  admin: coderzc                        # 'GitHub repo'
#  repo:  https://github.com/coderzc/coderzc.github.io                         # ['GitHub repo owner and collaborators, only these guys can initialize github issues']
#  clientID:                       # 'GitHub Application Client ID'
#  clientSecret:                   # 'GitHub Application Client Secret'
#  perPage: 10                     # Pagination size, with maximum 100.
#  pagerDirection: last            # Comment sorting direction, available values are last and first.
#  createIssueManually: false      # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true
#  language: en                    # Localization language key, en, zh-CN and zh-TW are currently available.
#  maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded.Default 250.
#  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token  # GitHub oauth request reverse proxy for CORS. For example, the demo url is 'https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token'.You should deploy your own proxy url as in this issue https://github.com/gitalk/gitalk/issues/429.


## Gitment Settings
## Doc:https://github.com/imsun/gitment
##
# gitment:
#   owner:                          # Your GitHub ID. Required.
#   repo:                           # The repository to store your comments. Make sure you're repo's owner. Required.
#   client_id:                      # GitHub client ID. Required.
#   client_secret:                  # GitHub client secret. Required.
#   desc:                           # An optional description for your page, used in issue's body. Default ''.
#   perPage: 10                     # An optional number to which comments will be paginated. Default 20.
#   maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded. Default 250.

## Disqus settings
##
# disqus_username: your-disqus-ID


# Analytics settings

## Google Analytics
ga_track_id: UA-xxxxxx-xx   # Format: UA-xxxxxx-xx

## Baidu Analytics
ba_track_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## Sitemap
sitemap:
  path: sitemap.xml

## Baidusitemap
baidusitemap:
  path: baidusitemap.xml

baidu_push: true

# Custom Setting End


# Directory
source_dir: source
public_dir: ../public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md    # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false    # Transform title into titlecase
# New option
# https://hexo.io/docs/configuration.html#Writing
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
  theme: atom-one-dark
  theme_dark: atom-one-dark
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
hljs:
  enable: true #true to enable the plugin
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code


# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true    # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# New option
# https://hexo.io/docs/configuration#Date-Time-format
updated_option: date


# Pagination
## Set per_page to 0 to disable pagination
##
per_page: 10
pagination_dir: archives

## Include / Exclude file(s)
### include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore: "**/note"

# hexo-generator-i18n config
## Docs: https://github.com/xcatliu/hexo-generator-index-i18n
index_generator:
  per_page: 10
  pagination_dir: page
  path: ''
  order_by: -date

archive_generator:
  enabled: false
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

## Markdown-it config
### Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  anchors:
    #创建 ID 的最低级别。(例如 h2 到 h6) 
    level : 1 
    #如果 ID 重复，则附加到给定数字的后缀。
    collisionSuffix : ' '            
    #如果 `true`，则创建一个锚标签，除了标题之外还有一个固定链接。
    permalink : false               
    #用于永久链接锚标记的类。
    permalinkClass : header-anchor 
    #设置为 'right' 以在标题后添加永久
    permalinkSide : ' left ' 
    #用于制作永久
    permalinkSymbol : ¶ 
    #将锚点转换为 (1) 小写；（2）上壳体




toc:
  maxdepth: 5
  slugify: transliteration
  decodeEntities: false

# Build Settings
anchorjs: false    # if you want to customize anchor. check out line:26 of `anchorjs.ejs`


# article top
top: true


# WordCount Settings
## Dependencies: https://github.com/willin/hexo-wordcount
## Docs: https://www.npmjs.com/package/hexo-wordcount
##
wordcount: false


# Busuanzi Settings
## Dependencies: https://busuanzi.ibruce.info/
## Docs: https://ibruce.info/
busuanzi: true


# top scroll progress
scroll: false


# Tip
tip:
  enable: false
#  copyright: 如果你喜欢这个博客或者觉得它对你有用，欢迎你评论。也欢迎大家分享这个博客，让更多的人参与进来。如果博客中使用的图片侵犯了您的版权，请联系作者删除。谢谢 !


# Social Share Post
## Docs:https://github.com/overtrue/share.js
##
socialshare: false


# Viewer config
## Docs:https://github.com/fengyuanchen/viewer
## Demo:https://fengyuanchen.github.io/viewer/
##
viewer: true


# ThemeColor config
themecolor:
  enable: true
  mode: light # themecolor mode light or dark, default light


# Mouseclick config
#mouseclick:
#  enable: false
#  content:
#    - The first step is as good as half over...
#    - Laugh and grow fat...
#    - Man proposes God disposes...
#    - When all else is lost the future still remains...
#    - Wasting time is robbing oneself...
#    - Sharp tools make good work...
#    - Cease to struggle and you cease to live...
#    - A friend in need is a friend indeed...
#    - Faith can move mountains...
#  color:
#    - '#9933CC'
#    - '#339933'
#    - '#66CCCC'
#    - '#FF99CC'
#    - '#CCCCFF'
#    - '#6666CC'
#    - '#663399'
#    - '#66CC99'
#    - '#FF0033'


# Ribbon config
ribbonDynamic: true


# Line config
bglinecanvas: false  # The special effects will take up a lot of cpu resorces, please open it carefully.


# Search Setting
## Search: https://go.kieran.top/post/45/
## Dependencies: https://github.com/V-Vincen/hexo-generator-zip-search
##
search:
  path: search.json
  zipPath: search.flv
  versionPath: searchVersion.json
  field: post
  trigger: auto   # if 'auto', trigger search by changing input;if 'manual', trigger search by pressing enter key or search button
  top_n_per_article: 1    # show top n results per article, show all results by setting to -1

# Theme config
## Themes: https://hexo.io/themes/
##
theme: livemylife


# Gitter
## Docs:https://gitter.im/?utm_source=left-menu-logo
##
#gitter:
#  room: your-community/your-room

# mathjax:
#   version: "v3"
