name: Publish hugegraph-computer image

on:
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'hugegraph/hugegraph-computer'
      repository_branch:
        required: true
        default: 'master'
      framework_image_url:
        required: true
        default: 'czcoder/hugegraph-computer-framework:test'
      algorithm_image_url:
        required: true
        default: 'czcoder/hugegraph-builtin-algorithms:test'
      operator_image_url:
        required: true
        default: 'czcoder/hugegraph-computer-operator:test'
      docker_registry_url:
        required: false
        default: ''
      replace_jar:
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ github.event.inputs.docker_registry_url }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository_url }}
          ref: ${{ github.event.inputs.repository_branch }}
          fetch-depth: 2    
          
      - name: Replace jar
        if: github.event.inputs.replace_jar == 'true'
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: |
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-client-1.9.7.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-client -Dversion=1.9.7 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/client-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-common-1.8.9.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-common -Dversion=1.8.9 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/common-pom.xml           

      - name: Build images
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: $TRAVIS_DIR/build-images.sh ${{ github.event.inputs.framework_image_url }} ${{ github.event.inputs.algorithm_image_url }} ${{ github.event.inputs.operator_image_url }}

      - name: Docker images
        run: docker images

      - name: Publish
        run: |
          docker push ${{ github.event.inputs.framework_image_url }}
          docker push ${{ github.event.inputs.algorithm_image_url }}
          docker push ${{ github.event.inputs.operator_image_url }}
          
