name: Publish hugegraph-computer image

on:
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'hugegraph/hugegraph-computer'
      repository_branch:
        required: true
        default: 'master'
      framework_image_url:
        required: true
      algorithm_image_url:
        required: true
      docker_registry_url:
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository_url }}
          ref: ${{ github.event.inputs.repository_branch }}
          fetch-depth: 2      
        
      - name: Build Project
        run: bash computer-dist/builddocker.sh
        
      - name: Docker build
        run: |
          PROJECT_VERSION=$(mvn -f "./pom.xml" -q -N \
          org.codehaus.mojo:exec-maven-plugin:1.3.1:exec \
          -Dexec.executable='echo' -Dexec.args='${project.version}')
          
          docker tag hugegraph/hugegraph-computer-framework:${PROJECT_VERSION} ${{ github.event.inputs.framework_image_url }}

          echo "FROM ${{ github.event.inputs.framework_image_url }}
          LABEL maintainer='HugeGraph Docker Maintainers <hugegraph@googlegroups.com>'
          COPY target/computer-algorithm-*.jar /opt/jars/computer-algorithm-based.jar
          ENV JAR_FILE_PATH=/opt/jars/computer-algorithm-based.jar" | \
          docker build -t ${{ github.event.inputs.algorithm_image_url }} -f - ./computer-algorithm
        
      - name: Docker images
        run: docker images

      - name: Publish
        run: |
          docker push ${{ github.event.inputs.framework_image_url }}
          docker push ${{ github.event.inputs.algorithm_image_url }}   
        
