name: Publish hugegraph image

on:
  workflow_dispatch:
    inputs:
      docker_file_url:
        required: true
        default: 'https://raw.githubusercontent.com/hugegraph/hugegraph/master/Dockerfile'
      image_url:
        required: true
        default: 'hugegraph/hugegraph:latest'
      docker_registry_url:
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ github.event.inputs.docker_registry_url }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker build
        run: |
          wget -c ${{ github.event.inputs.docker_file_url }} -O Dockerfile
          docker build -t ${{ github.event.inputs.image_url }} -f ./Dockerfile
        
      - name: Docker images
        run: docker images

      - name: Publish
        run: |
          docker push ${{ github.event.inputs.image_url }}
