name: Run Titannet

on:
  workflow_dispatch:

jobs:
   run-meson:
    runs-on: ubuntu-latest

    steps:
      - name: run
        run: |
              rm -rf ~/install.sh && wget https://raw.githubusercontent.com/qingjiuzys/titan-start/main/install.sh && chmod +x install.sh && sudo ./install.sh --type=1 --storage=8 --code=805533B6-0079-4CF8-AD21-8D85A8B81892
            
            
