name: Run titannet-docker

on:
  workflow_dispatch:

jobs:
   run-titan-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: run
        run: |
              cd titan/
              sudo chmod +x ./titan_start.sh
              echo ${{ env.TITAN_CODE }}
              ./titan_start.sh ${{ env.TITAN_CODE }}
              while true; do sleep 10000; done
