name: Run Titannet

on:
  workflow_dispatch:

jobs:
   run-meson:
    runs-on: ubuntu-latest

    steps:
      - name: run
        run: |
            wget -q -O titan_v0.1.16_linux_amd64.tar.gz https://github.com/Titannet-dao/titan-node/releases/download/v0.1.16/titan_v0.1.16_linux_amd64.tar.gz
            tar -zxf titan_v0.1.16_linux_amd64.tar.gz && cd ./titan_v0.1.16_linux_amd64
            ./titan-edge daemon start --init --url https://test-locator.titannet.io:5000/rpc/v0
            ./titan-edge bind --hash=5ACE5217-77BE-495C-85F1-059C3F5A9CD5 https://api-test1.container1.titannet.io/api/v2/device/binding
            ./titan-edge daemon stop
            ./titan-edge daemon start --init --url https://test-locator.titannet.io:5000/rpc/v0
            
            
