name: Run titannet-docker

on:
 # schedule:
    # - cron: '*/30 * * * *'
 workflow_dispatch:
   inputs:
        node_id:
          required: true
          default: '0'

jobs:
   run-titan-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache Primes
        id: cache-data
        uses: actions/cache@v4
        with:
          path: /home/runner/.titanedge
          key: ${{ runner.os }}-titan-${{ inputs.node_id }}          
              
      - name: run
        run: |
              cd titan/ 
              sudo chmod +x ./titan_start.sh
              ./titan_start.sh ${{ vars.TITAN_CODE }}
              docker ps
              sleep 20880s

      - name: Auth
        run: |
              sudo chmod -R 777 /home/runner/.titanedge
