name: Run titannet-docker

on:
  workflow_dispatch:

jobs:
   run-titan-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: run
        run: |
              cd titan/ 
              sudo chmod +x ./titan_start.sh
              ./titan_start.sh ${{ vars.TITAN_CODE }}
              while true; do sleep 10000; done
